catalog:
  '@antfu/eslint-config': ^6.2.0
  '@nuxt/eslint': ^1.10.0
  '@nuxt/image': ^2.0.0
  '@nuxt/ui': ^4.2.1
  eslint: ^9.39.1
  eslint-plugin-format: ^1.0.2
  nuxt: ^4.2.1
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  vue: ^3.5.25
  vue-router: ^4.6.3
  vue-tsc: ^3.1.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
