catalog:
  '@antfu/eslint-config': ^5.3.0
  '@nuxt/eslint': 1.9.0
  '@nuxt/image': 1.11.0
  '@nuxt/ui': 4.0.0-alpha.1
  eslint: ^9.35.0
  eslint-plugin-format: ^1.0.1
  nuxt: ^4.1.1
  tailwindcss: ^4.1.13
  typescript: ^5.9.2
  vue: ^3.5.21
  vue-router: ^4.5.1
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
